/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AskRouteImport } from './routes/ask'
import { Route as IndexRouteImport } from './routes/index'
import { Route as QuestionsIndexRouteImport } from './routes/questions/index'
import { Route as QuestionsQuestionIdRouteImport } from './routes/questions/$questionId'
import { Route as QuestionsQuestionIdAnswersAnswerIdRouteImport } from './routes/questions/$questionId/answers/$answerId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AskRoute = AskRouteImport.update({
  id: '/ask',
  path: '/ask',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestionsIndexRoute = QuestionsIndexRouteImport.update({
  id: '/questions/',
  path: '/questions/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestionsQuestionIdRoute = QuestionsQuestionIdRouteImport.update({
  id: '/questions/$questionId',
  path: '/questions/$questionId',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestionsQuestionIdAnswersAnswerIdRoute =
  QuestionsQuestionIdAnswersAnswerIdRouteImport.update({
    id: '/answers/$answerId',
    path: '/answers/$answerId',
    getParentRoute: () => QuestionsQuestionIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ask': typeof AskRoute
  '/login': typeof LoginRoute
  '/questions/$questionId': typeof QuestionsQuestionIdRouteWithChildren
  '/questions/': typeof QuestionsIndexRoute
  '/questions/$questionId/answers/$answerId': typeof QuestionsQuestionIdAnswersAnswerIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ask': typeof AskRoute
  '/login': typeof LoginRoute
  '/questions/$questionId': typeof QuestionsQuestionIdRouteWithChildren
  '/questions': typeof QuestionsIndexRoute
  '/questions/$questionId/answers/$answerId': typeof QuestionsQuestionIdAnswersAnswerIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ask': typeof AskRoute
  '/login': typeof LoginRoute
  '/questions/$questionId': typeof QuestionsQuestionIdRouteWithChildren
  '/questions/': typeof QuestionsIndexRoute
  '/questions/$questionId/answers/$answerId': typeof QuestionsQuestionIdAnswersAnswerIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ask'
    | '/login'
    | '/questions/$questionId'
    | '/questions/'
    | '/questions/$questionId/answers/$answerId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ask'
    | '/login'
    | '/questions/$questionId'
    | '/questions'
    | '/questions/$questionId/answers/$answerId'
  id:
    | '__root__'
    | '/'
    | '/ask'
    | '/login'
    | '/questions/$questionId'
    | '/questions/'
    | '/questions/$questionId/answers/$answerId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AskRoute: typeof AskRoute
  LoginRoute: typeof LoginRoute
  QuestionsQuestionIdRoute: typeof QuestionsQuestionIdRouteWithChildren
  QuestionsIndexRoute: typeof QuestionsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ask': {
      id: '/ask'
      path: '/ask'
      fullPath: '/ask'
      preLoaderRoute: typeof AskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/questions/': {
      id: '/questions/'
      path: '/questions'
      fullPath: '/questions/'
      preLoaderRoute: typeof QuestionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/questions/$questionId': {
      id: '/questions/$questionId'
      path: '/questions/$questionId'
      fullPath: '/questions/$questionId'
      preLoaderRoute: typeof QuestionsQuestionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/questions/$questionId/answers/$answerId': {
      id: '/questions/$questionId/answers/$answerId'
      path: '/answers/$answerId'
      fullPath: '/questions/$questionId/answers/$answerId'
      preLoaderRoute: typeof QuestionsQuestionIdAnswersAnswerIdRouteImport
      parentRoute: typeof QuestionsQuestionIdRoute
    }
  }
}

interface QuestionsQuestionIdRouteChildren {
  QuestionsQuestionIdAnswersAnswerIdRoute: typeof QuestionsQuestionIdAnswersAnswerIdRoute
}

const QuestionsQuestionIdRouteChildren: QuestionsQuestionIdRouteChildren = {
  QuestionsQuestionIdAnswersAnswerIdRoute:
    QuestionsQuestionIdAnswersAnswerIdRoute,
}

const QuestionsQuestionIdRouteWithChildren =
  QuestionsQuestionIdRoute._addFileChildren(QuestionsQuestionIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AskRoute: AskRoute,
  LoginRoute: LoginRoute,
  QuestionsQuestionIdRoute: QuestionsQuestionIdRouteWithChildren,
  QuestionsIndexRoute: QuestionsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
